/**
 * 获取单词的IPA音标
 * 使用免费字典API获取音标数据
 */

export interface WordPhonetic {
  word: string
  ipa: string
  audio?: string
}

export interface SentencePhonetics {
  original: string
  phonetic: string
  words: Array<{
    word: string
    ipa: string
  }>
}

/**
 * 从DictionaryAPI获取单词音标
 */
async function getWordPhonetic(word: string): Promise<string | null> {
  try {
    const response = await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word}`)

    if (!response.ok) {
      return null
    }

    const data = await response.json()

    if (data && data.length > 0 && data[0].phonetics) {
      // 查找包含音标的phonetic
      const phoneticWithText = data[0].phonetics.find((p: any) => p.text)
      return phoneticWithText?.text || null
    }

    return null
  } catch (error) {
    console.log(`获取单词 ${word} 音标失败:`, error)
    return null
  }
}

/**
 * 为句子生成音标标注
 * 每个单词后面用 /.../ 显示音标
 */
export async function generateSentencePhonetics(sentence: string): Promise<SentencePhonetics> {
  // 移除标点符号，保留单词
  const words = sentence.match(/\b[\w']+\b/g) || []

  const wordPhonetics: Array<{ word: string; ipa: string }> = []

  for (const word of words) {
    if (!word) continue
    const ipa = await getWordPhonetic(word.toLowerCase())
    wordPhonetics.push({
      word,
      ipa: ipa || ''
    })
  }

  // 生成完整音标字符串
  const phonetic = wordPhonetics
    .map(wp => wp.ipa ? `${wp.word} /${wp.ipa}/` : wp.word)
    .join(' ')

  return {
    original: sentence,
    phonetic,
    words: wordPhonetics
  }
}

/**
 * 简单版音标生成（使用本地规则，不需要API）
 * 适用于常见单词
 */
function getCommonPhoneticsDictionary(): Record<string, string> {
  return {
    'hello': '/həˈloʊ/',
    'world': '/wɜːrld/',
    'how': '/haʊ/',
    'are': '/ɑːr/',
    'you': '/juː/',
    'thank': '/θæŋk/',
    'welcome': '/ˈwelkəm/',
    'good': '/ɡʊd/',
    'morning': '/ˈmɔːrnɪŋ/',
    'night': '/naɪt/',
    'yes': '/jes/',
    'no': '/noʊ/',
    'please': '/pliːz/',
    'love': '/lʌv/',
    'like': '/laɪk/',
    'want': '/wɑːnt/',
    'need': '/niːd/',
    'know': '/noʊ/',
    'think': '/θɪŋk/',
    'time': '/taɪm/',
    'see': '/siː/',
    'come': '/kʌm/',
    'go': '/ɡoʊ/',
    'make': '/meɪk/',
    'take': '/teɪk/',
    'look': '/lʊk/',
    'give': '/ɡɪv/',
    'find': '/faɪnd/',
    'tell': '/tel/',
    'ask': '/æsk/',
    'work': '/wɜːrk/',
    'call': '/kɔːl/',
    'try': '/traɪ/',
    'use': '/juːz/',
    'live': '/lɪv/',
    'feel': '/fiːl/',
    'leave': '/liːv/',
    'put': '/pʊt/',
    'mean': '/miːn/',
    'keep': '/kiːp/',
    'let': '/let/',
    'begin': '/bɪˈɡɪn/',
    'seem': '/siːm/',
    'help': '/help/',
    'talk': '/tɔːk/',
    'turn': '/tɜːrn/',
    'start': '/stɑːrt/',
    'show': '/ʃoʊ/',
    'hear': '/hɪr/',
    'play': '/pleɪ/',
    'run': '/rʌn/',
    'move': '/muːv/',
    'enjoy': '/ɪnˈdʒɔɪ/',
    'happy': '/ˈhæpi/',
    'sad': '/sæd/',
    'beautiful': '/ˈbjuːtɪfl/',
    'important': '/ɪmˈpɔːrtənt/',
    'different': '/ˈdɪfrənt/',
    'every': '/ˈevri/',
    'other': '/ˈʌðər/',
    'people': '/ˈpiːpl/',
    'thing': '/θɪŋ/',
    'something': '/ˈsʌmθɪŋ/',
    'nothing': '/ˈnʌθɪŋ/',
    'about': '/əˈbaʊt/',
    'through': '/θruː/',
    'before': '/bɪˈfɔːr/',
    'after': '/ˈæftər/',
    'just': '/dʒʌst/',
    'also': '/ˈɔːlsoʊ/',
    'very': '/ˈveri/',
    'well': '/wel/',
    'much': '/mʌtʃ/',
    'more': '/mɔːr/',
    'most': '/moʊst/',
    'some': '/sʌm/',
    'such': '/sʌtʃ/',
    'only': '/ˈoʊnli/',
    'own': '/oʊn/',
    'same': '/seɪm/',
    'so': '/soʊ/',
    'than': '/ðæn/',
    'too': '/tuː/',
    'new': '/nuː/',
    'first': '/fɜːrst/',
    'last': '/læst/',
    'long': '/lɔːŋ/',
    'great': '/ɡreɪt/',
    'little': '/ˈlɪtl/',
    'old': '/oʊld/',
    'right': '/raɪt/',
    'big': '/bɪɡ/',
    'small': '/smɔːl/',
    'high': '/haɪ/',
    'low': '/loʊ/',
    'always': '/ˈɔːlweɪz/',
    'never': '/ˈnevər/',
    'today': '/təˈdeɪ/',
    'tomorrow': '/təˈmɑːroʊ/',
    'yesterday': '/ˈjestərdeɪ/',
    'week': '/wiːk/',
    'year': '/jɪr/',
    'day': '/deɪ/',
    'month': '/mʌnθ/',
    'home': '/hoʊm/',
    'house': '/haʊs/',
    'family': '/ˈfæməli/',
    'friend': '/frend/',
    'school': '/skuːl/',
    'job': '/dʒɑːb/',
    'money': '/ˈmʌni/',
    'food': '/fuːd/',
    'water': '/ˈwɔːtər/',
    'question': '/ˈkwestʃən/',
    'answer': '/ˈænsər/',
    'learn': '/lɜːrn/',
    'study': '/ˈstʌdi/',
    'read': '/riːd/',
    'write': '/raɪt/',
    'speak': '/spiːk/',
    'listen': '/ˈlɪsən/',
    'understand': '/ˌʌndərˈstænd/',
    'watch': '/wɑːtʃ/',
    'happen': '/ˈhæpən/',
    'really': '/ˈriːəli/',
    'probably': '/ˈprɑːbəbli/',
    'actually': '/ˈæktʃuəli/',
    'already': '/ɔːlˈredi/',
    'together': '/təˈɡeðər/',
    'again': '/əˈɡen/',
    'once': '/wʌns/',
    'here': '/hɪr/',
    'there': '/ðer/',
    'where': '/wer/',
    'when': '/wen/',
    'why': '/waɪ/',
    'what': '/wʌt/',
    'which': '/wɪtʃ/',
    'who': '/huː/',
    'this': '/ðɪs/',
    'that': '/ðæt/',
    'these': '/ðiːz/',
    'those': '/ðoʊz/',
    'be': '/biː/',
    'is': '/ɪz/',
    'am': '/æm/',
    'was': '/wʌz/',
    'were': '/wɜːr/',
    'been': '/bɪn/',
    'being': '/ˈbiːɪŋ/',
    'have': '/hæv/',
    'has': '/hæz/',
    'had': '/hæd/',
    'having': '/ˈhævɪŋ/',
    'do': '/duː/',
    'does': '/dʌz/',
    'did': '/dɪd/',
    'done': '/dʌn/',
    'doing': '/ˈduːɪŋ/',
    'say': '/seɪ/',
    'said': '/sed/',
    'get': '/ɡet/',
    'got': '/ɡɑːt/',
    'getting': '/ˈɡetɪŋ/',
    'made': '/meɪd/',
    'making': '/ˈmeɪkɪŋ/',
    'went': '/went/',
    'gone': '/ɡɔːn/',
    'going': '/ˈɡoʊɪŋ/',
    'knew': '/nuː/',
    'known': '/noʊn/',
    'knowing': '/ˈnoʊɪŋ/',
    'took': '/tʊk/',
    'taken': '/ˈteɪkən/',
    'taking': '/ˈteɪkɪŋ/',
    'came': '/keɪm/',
    'coming': '/ˈkʌmɪŋ/',
    'thought': '/θɔːt/',
    'thinking': '/ˈθɪŋkɪŋ/',
    'saw': '/sɔː/',
    'seen': '/siːn/',
    'seeing': '/ˈsiːɪŋ/',
    'wanted': '/ˈwɑːntɪd/',
    'wanting': '/ˈwɑːntɪŋ/',
    'looking': '/ˈlʊkɪŋ/',
    'used': '/juːzd/',
    'using': '/ˈjuːzɪŋ/',
    'found': '/faʊnd/',
    'finding': '/ˈfaɪndɪŋ/',
    'gave': '/ɡeɪv/',
    'given': '/ˈɡɪvən/',
    'giving': '/ˈɡɪvɪŋ/',
    'told': '/toʊld/',
    'telling': '/ˈtelɪŋ/',
    'worked': '/wɜːrkt/',
    'working': '/ˈwɜːrkɪŋ/',
    'called': '/kɔːld/',
    'calling': '/ˈkɔːlɪŋ/',
    'tried': '/traɪd/',
    'trying': '/ˈtraɪɪŋ/',
    'needed': '/ˈniːdɪd/',
    'needing': '/ˈniːdɪŋ/',
    'felt': '/felt/',
    'feeling': '/ˈfiːlɪŋ/',
    'become': '/bɪˈkʌm/',
    'became': '/bɪˈkeɪm/',
    'becoming': '/bɪˈkʌmɪŋ/',
    'left': '/left/',
    'leaving': '/ˈliːvɪŋ/',
    'putting': '/ˈpʊtɪŋ/',
    'meant': '/ment/',
    'meaning': '/ˈmiːnɪŋ/',
    'kept': '/kept/',
    'keeping': '/ˈkiːpɪŋ/',
    'letting': '/ˈletɪŋ/',
    'began': '/bɪˈɡæn/',
    'begun': '/bɪˈɡʌn/',
    'beginning': '/bɪˈɡɪnɪŋ/',
    'seemed': '/siːmd/',
    'seeming': '/ˈsiːmɪŋ/',
    'helped': '/helpt/',
    'helping': '/ˈhelpɪŋ/',
    'shown': '/ʃoʊn/',
    'showing': '/ˈʃoʊɪŋ/',
    'heard': '/hɜːrd/',
    'hearing': '/ˈhɪrɪŋ/',
    'played': '/pleɪd/',
    'playing': '/ˈpleɪɪŋ/',
    'ran': '/ræn/',
    'running': '/ˈrʌnɪŋ/',
    'moved': '/muːvd/',
    'moving': '/ˈmuːvɪŋ/',
    'lived': '/lɪvd/',
    'living': '/ˈlɪvɪŋ/',
    'believe': '/bɪˈliːv/',
    'believed': '/bɪˈliːvd/',
    'believing': '/bɪˈliːvɪŋ/',
    'hold': '/hoʊld/',
    'held': '/held/',
    'holding': '/ˈhoʊldɪŋ/',
    'bring': '/brɪŋ/',
    'brought': '/brɔːt/',
    'bringing': '/ˈbrɪŋɪŋ/',
    'happened': '/ˈhæpənd/',
    'happening': '/ˈhæpənɪŋ/',
    'wrote': '/roʊt/',
    'written': '/ˈrɪtən/',
    'writing': '/ˈraɪtɪŋ/',
    'sit': '/sɪt/',
    'sat': '/sæt/',
    'sitting': '/ˈsɪtɪŋ/',
    'stand': '/stænd/',
    'stood': '/stʊd/',
    'standing': '/ˈstændɪŋ/',
    'lose': '/luːz/',
    'lost': '/lɔːst/',
    'losing': '/ˈluːzɪŋ/',
    'pay': '/peɪ/',
    'paid': '/peɪd/',
    'paying': '/ˈpeɪɪŋ/',
    'meet': '/miːt/',
    'met': '/met/',
    'meeting': '/ˈmiːtɪŋ/',
    'learned': '/lɜːrnd/',
    'learning': '/ˈlɜːrnɪŋ/',
    'change': '/tʃeɪndʒ/',
    'changed': '/tʃeɪndʒd/',
    'changing': '/ˈtʃeɪndʒɪŋ/',
    'lead': '/liːd/',
    'led': '/led/',
    'leading': '/ˈliːdɪŋ/',
    'understood': '/ˌʌndərˈstʊd/',
    'understanding': '/ˌʌndərˈstændɪŋ/',
    'watched': '/wɑːtʃt/',
    'watching': '/ˈwɑːtʃɪŋ/',
    'follow': '/ˈfɑːloʊ/',
    'followed': '/ˈfɑːloʊd/',
    'following': '/ˈfɑːloʊɪŋ/',
    'stop': '/stɑːp/',
    'stopped': '/stɑːpt/',
    'stopping': '/ˈstɑːpɪŋ/',
    'create': '/kriˈeɪt/',
    'created': '/kriˈeɪtɪd/',
    'creating': '/kriˈeɪtɪŋ/',
    'spoke': '/spoʊk/',
    'spoken': '/ˈspoʊkən/',
    'speaking': '/ˈspiːkɪŋ/',
    'reading': '/ˈriːdɪŋ/',
    'spend': '/spend/',
    'spent': '/spent/',
    'spending': '/ˈspendɪŋ/',
    'grow': '/ɡroʊ/',
    'grew': '/ɡruː/',
    'grown': '/ɡroʊn/',
    'growing': '/ˈɡroʊɪŋ/',
    'open': '/ˈoʊpən/',
    'opened': '/ˈoʊpənd/',
    'opening': '/ˈoʊpənɪŋ/',
    'walk': '/wɔːk/',
    'walked': '/wɔːkt/',
    'walking': '/ˈwɔːkɪŋ/',
    'win': '/wɪn/',
    'won': '/wʌn/',
    'winning': '/ˈwɪnɪŋ/',
    'offer': '/ˈɔːfər/',
    'offered': '/ˈɔːfərd/',
    'offering': '/ˈɔːfərɪŋ/',
    'remember': '/rɪˈmembər/',
    'remembered': '/rɪˈmembərd/',
    'remembering': '/rɪˈmembərɪŋ/',
    'loved': '/lʌvd/',
    'loving': '/ˈlʌvɪŋ/',
    'consider': '/kənˈsɪdər/',
    'considered': '/kənˈsɪdərd/',
    'considering': '/kənˈsɪdərɪŋ/',
    'appear': '/əˈpɪr/',
    'appeared': '/əˈpɪrd/',
    'appearing': '/əˈpɪrɪŋ/',
    'buy': '/baɪ/',
    'bought': '/bɔːt/',
    'buying': '/ˈbaɪɪŋ/',
    'wait': '/weɪt/',
    'waited': '/ˈweɪtɪd/',
    'waiting': '/ˈweɪtɪŋ/',
    'serve': '/sɜːrv/',
    'served': '/sɜːrvd/',
    'serving': '/ˈsɜːrvɪŋ/',
    'die': '/daɪ/',
    'died': '/daɪd/',
    'dying': '/ˈdaɪɪŋ/',
    'send': '/send/',
    'sent': '/sent/',
    'sending': '/ˈsendɪŋ/',
    'expect': '/ɪkˈspekt/',
    'expected': '/ɪkˈspektɪd/',
    'expecting': '/ɪkˈspektɪŋ/',
    'build': '/bɪld/',
    'built': '/bɪlt/',
    'building': '/ˈbɪldɪŋ/',
    'stay': '/steɪ/',
    'stayed': '/steɪd/',
    'staying': '/ˈsteɪɪŋ/',
    'fall': '/fɔːl/',
    'fell': '/fel/',
    'fallen': '/ˈfɔːlən/',
    'falling': '/ˈfɔːlɪŋ/',
    'cut': '/kʌt/',
    'cutting': '/ˈkʌtɪŋ/',
    'reach': '/riːtʃ/',
    'reached': '/riːtʃt/',
    'reaching': '/ˈriːtʃɪŋ/',
    'kill': '/kɪl/',
    'killed': '/kɪld/',
    'killing': '/ˈkɪlɪŋ/',
    'remain': '/rɪˈmeɪn/',
    'remained': '/rɪˈmeɪnd/',
    'remaining': '/rɪˈmeɪnɪŋ/',
    'suggest': '/səˈdʒest/',
    'suggested': '/səˈdʒestɪd/',
    'suggesting': '/səˈdʒestɪŋ/',
    'raise': '/reɪz/',
    'raised': '/reɪzd/',
    'raising': '/ˈreɪzɪŋ/',
    'pass': '/pæs/',
    'passed': '/pæst/',
    'passing': '/ˈpæsɪŋ/',
    'sell': '/sel/',
    'sold': '/soʊld/',
    'selling': '/ˈselɪŋ/',
    'require': '/rɪˈkwaɪər/',
    'required': '/rɪˈkwaɪərd/',
    'requiring': '/rɪˈkwaɪərɪŋ/',
    'report': '/rɪˈpɔːrt/',
    'reported': '/rɪˈpɔːrtɪd/',
    'reporting': '/rɪˈpɔːrtɪŋ/',
    'decide': '/dɪˈsaɪd/',
    'decided': '/dɪˈsaɪdɪd/',
    'deciding': '/dɪˈsaɪdɪŋ/',
    'pull': '/pʊl/',
    'pulled': '/pʊld/',
    'pulling': '/ˈpʊlɪŋ/',
    'develop': '/dɪˈveləp/',
    'developed': '/dɪˈveləpt/',
    'developing': '/dɪˈveləpɪŋ/',
    'end': '/end/',
    'ended': '/ˈendɪd/',
    'ending': '/ˈendɪŋ/',
    'receive': '/rɪˈsiːv/',
    'received': '/rɪˈsiːvd/',
    'receiving': '/rɪˈsiːvɪŋ/',
    'join': '/dʒɔɪn/',
    'joined': '/dʒɔɪnd/',
    'joining': '/ˈdʒɔɪnɪŋ/',
    'cause': '/kɔːz/',
    'caused': '/kɔːzd/',
    'causing': '/ˈkɔːzɪŋ/',
    'allow': '/əˈlaʊ/',
    'allowed': '/əˈlaʊd/',
    'allowing': '/əˈlaʊɪŋ/',
    'accept': '/əkˈsept/',
    'accepted': '/əkˈseptɪd/',
    'accepting': '/əkˈseptɪŋ/',
    'agree': '/əˈɡriː/',
    'agreed': '/əˈɡriːd/',
    'agreeing': '/əˈɡriːɪŋ/',
    'wear': '/wer/',
    'wore': '/wɔːr/',
    'worn': '/wɔːrn/',
    'wearing': '/ˈwerɪŋ/',
    'choose': '/tʃuːz/',
    'chose': '/tʃoʊz/',
    'chosen': '/ˈtʃoʊzən/',
    'choosing': '/ˈtʃuːzɪŋ/',
    'encourage': '/ɪnˈkɜːrɪdʒ/',
    'encouraged': '/ɪnˈkɜːrɪdʒd/',
    'encouraging': '/ɪnˈkɜːrɪdʒɪŋ/',
    'hope': '/hoʊp/',
    'hoped': '/hoʊpt/',
    'hoping': '/ˈhoʊpɪŋ/',
    'achieve': '/əˈtʃiːv/',
    'achieved': '/əˈtʃiːvd/',
    'achieving': '/əˈtʃiːvɪŋ/',
    'improve': '/ɪmˈpruːv/',
    'improved': '/ɪmˈpruːvd/',
    'improving': '/ɪmˈpruːvɪŋ/',
    'success': '/səkˈses/',
    'failure': '/ˈfeɪljər/',
    'mistake': '/mɪˈsteɪk/',
    'problem': '/ˈprɑːbləm/',
    'solution': '/səˈluːʃn/',
    'opportunity': '/ˌɑːpərˈtuːnəti/',
    'experience': '/ɪkˈspɪriəns/',
    'knowledge': '/ˈnɑːlɪdʒ/',
    'information': '/ˌɪnfərˈmeɪʃn/',
    'attention': '/əˈtenʃn/',
    'condition': '/kənˈdɪʃn/',
    'situation': '/ˌsɪtʃuˈeɪʃn/',
    'education': '/ˌedʒuˈkeɪʃn/',
    'interesting': '/ˈɪntrəstɪŋ/',
    'necessary': '/ˈnesəseri/',
    'possible': '/ˈpɑːsəbl/',
    'difficult': '/ˈdɪfɪkəlt/',
    'easy': '/ˈiːzi/',
    'hard': '/hɑːrd/',
    'soft': '/sɔːft/',
    'exciting': '/ɪkˈsaɪtɪŋ/',
    'boring': '/ˈbɔːrɪŋ/',
    'wonderful': '/ˈwʌndərfl/',
    'terrible': '/ˈterəbl/',
    'amazing': '/əˈmeɪzɪŋ/',
    'awful': '/ˈɔːfl/',
    'excellent': '/ˈeksələnt/',
    'perfect': '/ˈpɜːrfekt/',
    'complete': '/kəmˈpliːt/',
    'simple': '/ˈsɪmpl/',
    'complex': '/kəmˈpleks/',
    'clear': '/klɪr/',
    'dark': '/dɑːrk/',
    'bright': '/braɪt/',
    'heavy': '/ˈhevi/',
    'light': '/laɪt/',
    'hot': '/hɑːt/',
    'cold': '/koʊld/',
    'warm': '/wɔːrm/',
    'cool': '/kuːl/',
    'fresh': '/freʃ/',
    'clean': '/kliːn/',
    'dirty': '/ˈdɜːrti/',
    'expensive': '/ɪkˈspensɪv/',
    'cheap': '/tʃiːp/',
    'free': '/friː/',
    'full': '/fʊl/',
    'empty': '/ˈempti/',
    'rich': '/rɪtʃ/',
    'poor': '/pɔːr/',
    'young': '/jʌŋ/',
    'modern': '/ˈmɑːdərn/',
    'ancient': '/ˈeɪnʃənt/',
    'public': '/ˈpʌblɪk/',
    'private': '/ˈpraɪvət/',
    'local': '/ˈloʊkl/',
    'international': '/ˌɪntərˈnæʃnəl/',
    'famous': '/ˈfeɪməs/',
    'popular': '/ˈpɑːpjələr/',
    'normal': '/ˈnɔːrml/',
    'strange': '/streɪndʒ/',
    'similar': '/ˈsɪmələr/',
    'able': '/ˈeɪbl/',
    'unable': '/ʌnˈeɪbl/',
    'available': '/əˈveɪləbl/',
    'responsible': '/rɪˈspɑːnsəbl/',
    'sure': '/ʃʊr/',
    'certain': '/ˈsɜːrtn/',
    'ready': '/ˈredi/',
    'busy': '/ˈbɪzi/',
    'careful': '/ˈkerfl/',
    'dangerous': '/ˈdeɪndʒərəs/',
    'safe': '/seɪf/',
    'healthy': '/ˈhelθi/',
    'sick': '/sɪk/',
    'lucky': '/ˈlʌki/',
    'tired': '/ˈtaɪərd/',
    'hungry': '/ˈhʌŋɡri/',
    'thirsty': '/ˈθɜːrsti/',
    'afraid': '/əˈfreɪd/',
    'worried': '/ˈwɜːrid/',
    'angry': '/ˈæŋɡri/',
    'proud': '/praʊd/',
    'nervous': '/ˈnɜːrvəs/',
    'calm': '/kɑːm/',
    'quiet': '/ˈkwaɪət/',
    'loud': '/laʊd/',
    'polite': '/pəˈlaɪt/',
    'rude': '/ruːd/',
    'kind': '/kaɪnd/',
    'cruel': '/ˈkruːəl/',
    'generous': '/ˈdʒenərəs/',
    'selfish': '/ˈselfɪʃ/',
    'honest': '/ˈɑːnɪst/',
    'dishonest': '/dɪsˈɑːnɪst/',
    'brave': '/breɪv/',
    'cowardly': '/ˈkaʊərdli/',
    'strong': '/strɔːŋ/',
    'weak': '/wiːk/',
    'smart': '/smɑːrt/',
    'stupid': '/ˈstuːpɪd/',
    'wise': '/waɪz/',
    'foolish': '/ˈfuːlɪʃ/',
    'creative': '/kriˈeɪtɪv/',
    'funny': '/ˈfʌni/',
    'serious': '/ˈsɪriəs/',
    'active': '/ˈæktɪv/',
    'lazy': '/ˈleɪzi/',
    'fast': '/fæst/',
    'slow': '/sloʊ/',
    'quick': '/kwɪk/',
    'early': '/ˈɜːrli/',
    'late': '/leɪt/',
    'recent': '/ˈriːsnt/',
    'soon': '/suːn/',
    'sometimes': '/ˈsʌmtaɪmz/',
    'often': '/ˈɔːfn/',
    'usually': '/ˈjuːʒuəli/',
    'generally': '/ˈdʒenrəli/',
    'finally': '/ˈfaɪnəli/',
    'suddenly': '/ˈsʌdənli/',
    'slowly': '/ˈsloʊli/',
    'quickly': '/ˈkwɪkli/',
    'carefully': '/ˈkerfəli/',
    'easily': '/ˈiːzəli/',
    'simply': '/sɪmpli/',
    'certainly': '/ˈsɜːrtnli/',
    'definitely': '/ˈdefənətli/',
    'exactly': '/ɪɡˈzæktli/',
    'especially': '/ɪˈspeʃəli/',
    'particularly': '/pərˈtɪkjələrli/',
    'completely': '/kəmˈpliːtli/',
    'almost': '/ˈɔːlmoʊst/',
    'hardly': '/ˈhɑːrdli/',
    'barely': '/ˈberli/',
    'nearly': '/ˈnɪrli/',
    'quite': '/kwaɪt/',
    'rather': '/ˈræðər/',
    'extremely': '/ɪkˈstriːmli/',
    'absolutely': '/ˈæbsəluːtli/',
    'totally': '/ˈtoʊtəli/',
    'even': '/ˈiːvn/',
    'still': '/stɪl/',
    'yet': '/jet/',
    'twice': '/twaɪs/',
    'forever': '/fərˈevər/',
    'I': '/aɪ/',
    'he': '/hiː/',
    'she': '/ʃiː/',
    'it': '/ɪt/',
    'we': '/wiː/',
    'they': '/ðeɪ/',
    'my': '/maɪ/',
    'your': '/jɔːr/',
    'his': '/hɪz/',
    'her': '/hɜːr/',
    'its': '/ɪts/',
    'our': '/aʊər/',
    'their': '/ðer/',
    'me': '/miː/',
    'him': '/hɪm/',
    'them': '/ðem/',
    'us': '/ʌs/',
    'mine': '/maɪn/',
    'yours': '/jɔːrz/',
    'hers': '/hɜːrz/',
    'ours': '/aʊərz/',
    'theirs': '/ðerz/',
    'a': '/ə/',
    'an': '/æn/',
    'the': '/ðə/',
    'and': '/ænd/',
    'but': '/bət/',
    'or': '/ɔːr/',
    'because': '/bɪˈkɔːz/',
    'although': '/ɔːlˈðoʊ/',
    'though': '/ðoʊ/',
    'while': '/waɪl/',
    'if': '/ɪf/',
    'unless': '/ənˈles/',
    'until': '/ənˈtɪl/',
    'since': '/sɪns/',
    'as': '/æz/',
    'both': '/boʊθ/',
    'either': '/ˈiːðər/',
    'neither': '/ˈniːðər/',
    'not': '/nɑːt/',
    'maybe': '/ˈmeɪbi/',
    'perhaps': '/pərˈhæps/',
    'possibly': '/ˈpɑːsəbli/',
    'thanks': '/θæŋks/',
    'sorry': '/ˈsɑːri/',
    'excuse': '/ɪkˈskjuːs/',
    'hi': '/haɪ/',
    'goodbye': '/ɡʊdˈbaɪ/',
    'bye': '/baɪ/',
    'ok': '/oʊˈkeɪ/',
    'okay': '/oʊˈkeɪ/',
    'fine': '/faɪn/',
    'bad': '/bæd/',
    'nice': '/naɪs/',
    'wrong': '/rɔːŋ/',
    'true': '/truː/',
    'false': '/fɔːls/',
  }
}

// 缓存字典以提高性能
const commonPhonetics = getCommonPhoneticsDictionary()

/**
 * 快速获取句子音标（使用本地词库）
 */
export function getQuickSentencePhonetics(sentence: string): SentencePhonetics {
  // 移除标点符号，保留单词
  const words = sentence.match(/\b[\w']+\b/g) || []

  const wordPhonetics: Array<{ word: string; ipa: string }> = []

  for (const word of words) {
    if (!word) continue
    const lowerWord = word.toLowerCase()
    const ipa = commonPhonetics[lowerWord] || ''
    wordPhonetics.push({
      word,
      ipa
    })
  }

  // 生成完整音标字符串
  const phonetic = wordPhonetics
    .map(wp => {
      // 如果是标点符号后的大写字母开头，保留原词
      if (wp.word === wp.word.toUpperCase() && wp.word.length > 0) {
        return wp.ipa ? `${wp.word} /${wp.ipa}/` : wp.word
      }
      return wp.ipa ? `${wp.word} /${wp.ipa}/` : wp.word
    })
    .join(' ')

  return {
    original: sentence,
    phonetic,
    words: wordPhonetics
  }
}
